### ISSUE TITLE
Does not work with Oracle Linux (which is RedHat/CentOS compatible)

### ISSUE THREAD

**Issue by annawake** [computology/packagecloud-cookbook#11]
Bombs with this error:

```
RuntimeError
-----------------
#<Net::HTTPNotFound 404 Not Found ready-true>
```

After tracing into the code, the issue appears to be here in providers/repo.rb:
https://github.com/computology/packagecloud-cookbook/blob/master/providers/repo.rb#L62

On Oracle Linux 6.5, the following values are passed in to the URI get:

```
base_url_endpoint = http://packagecloud.io/install/repositories/computology/packagecloud-cookbook-test-public/rpm_base_url
install_endpoint_params = {:os=>"oracle", :dist=>"6.5", :name=>"default-oel65.vagrantup.com"}
```

vs. on CentOS it's:

```
install_endpoint_params = {:os=>"centos", :dist=>"6.5", :name=>"default-centos-65.vagrantup.com")
```

On the other end, the packagecloud repo should accept oracle as an `:os` and handle it like centos.  I'm not sure if this is a packagecloud issue or a chef issue in populating the packages.

(I also suspect there will be similar issues with RedHat and Scientific Linux, if you haven't already tested these).

**Comment by afiune** [comment]
Agree! This it totally broken for `rpm` based os systems... Trying to fix it now..

**Comment by afiune** [comment]
Here is the fixes I made to let this cookbook work on RHEL/Centos family..  https://github.com/computology/packagecloud-cookbook/pull/14 

You can use my fork also.. :smile: 

https://github.com/afiune/packagecloud-cookbook

Cheers!

**Comment by ice799** [comment]
Hi, the `force_os` and `force_dist` options were added (check the docs for more info) that will let you override the OS detection if you like. I'm going to close this issue.
