### ISSUE TITLE
allow providing platform version via attributes

### ISSUE THREAD

**Issue by ranjib** [computology/packagecloud-cookbook#20]
currently the provider uses lsb attributed to derive these values. for system where lsb is not installed, this breaks the provider silently,. for cases where lsb is not available allow setting the platform version through the lwrp  or a default attribute .. like node.packagecloud.lsb_codename

**Comment by capotej** [comment]
This pull request that was just merged may help this issue: https://github.com/computology/packagecloud-cookbook/pull/32
