### ISSUE TITLE
Allow base_url to be specified by attribute to allow for local mirror

### ISSUE THREAD

**Issue by marcusn** [computology/packagecloud-cookbook#24]
Please allow the base_url for the repo resource to be overridden by an attribute. This allows for a local mirror in case internet is not allowed.

**Comment by capotej** [comment]
This pull request: https://github.com/computology/packagecloud-cookbook/pull/15 should help with this, please re-open this if it doesnt.

**Comment by marcusn** [comment]
It doesn't help when you want to override the baseurl globally and not change third party cookbooks that use the resource. 

I can recommend defaulting to the attribute in resource file with a lazy block around it, best of both worlds.
