### ISSUE TITLE
No link on supermarket

### ISSUE THREAD

**Issue by spuder** [computology/packagecloud-cookbook#29]
I'm assuming this is the same cookbook that is listed on the supermarket. 

https://supermarket.chef.io/cookbooks/packagecloud

If so, it would be nice if the supermarket linked to the source code. See this example:

![screenshot 2015-11-12 08 22 57](https://cloud.githubusercontent.com/assets/242382/11122075/a7a7859a-8916-11e5-8e71-fadc5b374601.png)

**Comment by capotej** [comment]
Any idea how to get this to work? It's linked correctly in our [metadata.rb](https://github.com/computology/packagecloud-cookbook/blob/master/metadata.rb#L8)

**Comment by spuder** [comment]
I have never done it myself, but I think you do it on the supermarket page itself, or when you upload the cookbook. 

When it is setup properly, the `source_url` and/or `issues_url` fields will be populated when you run this command

```ruby
knife cookbook site show packagecloud
average_rating:
category:           Other
created_at:         2014-06-06T03:02:37.000Z
deprecated:         false
description:        Installs/Configures packagecloud.io repositories.
external_url:
foodcritic_failure: true
issues_url:
latest_version:     https://supermarket.chef.io/api/v1/cookbooks/packagecloud/versions/0.1.0
maintainer:         jdamato
```

This blog talks more about it. 
https://www.chef.io/blog/2015/03/16/using-chef-supermarket-a-guided-tour/

**Comment by tas50** [comment]
If you use stove to upload the cookbook the new metadata will get stripped.  You'll need to log into the supermarket where you can add it via the UI.  It would be super useful to get this added.

**Comment by capotej** [comment]
Finally found out what to edit to fix this, should be updated now.

**Comment by spuder** [comment]
Thanks. Could you tell me how you did it? I'm uploading my first cookbook soon.

**Comment by tas50** [comment]
If you're ok with a cookbook being Chef 12+ only you can use stove --extended-metadata

**Comment by capotej** [comment]
I clicked on the little gear on the right hand side next to "details" and it let me fill them in

![screen shot 2015-11-24 at 1 06 56 pm](https://cloud.githubusercontent.com/assets/6135/11380667/50c83c52-92ac-11e5-8452-84d85c6be570.png)

**Comment by spuder** [comment]
Perfect, thank you.
