### ISSUE TITLE
Allow forcing of os/dist for repository install

### ISSUE THREAD

**Issue by capotej** [computology/packagecloud-cookbook#31]
Something like the following, equivalent to our [Manual Install Instructions](https://packagecloud.io/computology/packagecloud-cookbook-test-public/install#manual) but for chef.

```
packagecloud_repo "computology/packagecloud-cookbook-test-public" do
  type "deb"
  force_os "ubuntu"
  force_dist "warty"
end
```

**Comment by afiune** [comment]
:+1:
