### ISSUE TITLE
force_os and force_dist dont work for deb packages

### ISSUE THREAD

**Issue by woodsaj** [computology/packagecloud-cookbook#40]
https://github.com/computology/packagecloud-cookbook/issues/31 suggests that this feature was added, bit it only looks to have been added for rpm packages.

**Comment by eduaquiles** [comment]
I've also hit this issue

**Comment by ice799** [comment]
This was fixed with the merging of https://github.com/computology/packagecloud-cookbook/pull/41 thanks to @ctdk for the PR!
