### ISSUE TITLE
Tag 0.2.0 is not in git but version exists in supermarket

### ISSUE THREAD

**Issue by kamaradclimber** [computology/packagecloud-cookbook#49]
There is no tag 0.2.0 in this repo but the version exists in supermarket (https://supermarket.chef.io/cookbooks/packagecloud/versions/0.2.0).

We use tags to display changelog between two version when upgrading a cookbook (using knife-changelog gem).

Could you add the tag?

**Comment by ice799** [comment]
Fixed.
